# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [ ]:
#from sklearn import preprocessing
#le = preprocessing.LabelEncoder()

In [ ]:
#le.fit(df['home_ownership'])
#df['home_ownership'] = le.transform(df['home_ownership'])
# le.fit(df['loan_status'])
# df['loan_status'] = le.transform(df['loan_status'])
# le.fit(df['verification_status'])
# df['verification_status'] = le.transform(df['verification_status'])

## Split the Data into Training and Testing

In [5]:
# Create our features
X = df.drop(columns="loan_status")
X = pd.get_dummies(X)

# Create our target
y = df["loan_status"]

In [6]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [7]:
# Check the balance of our target values
# YOUR CODE HERE
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [8]:
# Split the X and y into X_train, X_test, y_train, y_test
# YOUR CODE HERE
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [9]:
# Create the StandardScaler instance
# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler

# YOUR CODE HERE
scaler = StandardScaler()

In [10]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE
X_scaler = scaler.fit(X_train)

In [11]:
# Scale the training and testing data
# YOUR CODE HERE
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=500, random_state=42)
rf_model = rf_model.fit(X_train_scaled, y_train)
predictions = rf_model.predict(X_test_scaled)

In [13]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, predictions)

0.6680938024317067

In [14]:
# Display the confusion matrix
# YOUR CODE HERE
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)
cm_df

          Predicted 0  Predicted 1
Actual 0           35           69
Actual 1            6        17095

In [15]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      0.34      1.00      0.48      0.58      0.31       104
   low_risk       1.00      1.00      0.34      1.00      0.58      0.36     17101

avg / total       1.00      1.00      0.34      0.99      0.58      0.36     17205

In [16]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
importances = rf_model.feature_importances_
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.07699153924161611, 'total_rec_int'),
 (0.06971219417575251, 'last_pymnt_amnt'),
 (0.06491253077608945, 'total_rec_prncp'),
 (0.06446237495842298, 'total_pymnt_inv'),
 (0.05508867414954958, 'total_pymnt'),
 (0.023015782089173802, 'installment'),
 (0.02008607915109398, 'out_prncp_inv'),
 (0.01955662969732199, 'out_prncp'),
 (0.016290120363713412, 'mo_sin_old_rev_tl_op'),
 (0.015849336997240913, 'dti'),
 (0.014758110394082976, 'revol_bal'),
 (0.01463689454625533, 'mo_sin_old_il_acct'),
 (0.014567767442776524, 'tot_cur_bal'),
 (0.014531251329738851, 'loan_amnt'),
 (0.014413400478274942, 'avg_cur_bal'),
 (0.01439432837099982, 'tot_hi_cred_lim'),
 (0.014390292846857052, 'max_bal_bc'),
 (0.013852817431769285, 'total_bal_ex_mort'),
 (0.013677697231735448, 'annual_inc'),
 (0.01350080172693217, 'total_bal_il'),
 (0.013387960126836355, 'bc_open_to_buy'),
 (0.013357697947199942, 'bc_util'),
 (0.013163738356893577, 'total_il_high_credit_limit'),
 (0.012998614166447108, 'total_bc_limit'),
 (0.012936580740762612, 'issue_d_Mar-2019'),
 (0.012817605240726495, 'il_util'),
 (0.012212738190167046, 'int_rate'),
 (0.01206162472837695, 'total_rev_hi_lim'),
 (0.012035885773174122, 'all_util'),
 (0.011514033793979346, 'mths_since_recent_bc'),
 (0.011477265845531458, 'mths_since_rcnt_il'),
 (0.010931185137295216, 'total_rec_late_fee'),
 (0.010523812664080494, 'total_acc'),
 (0.00999435485363663, 'num_rev_accts'),
 (0.009975530194439735, 'mths_since_recent_inq'),
 (0.009835403571895267, 'mo_sin_rcnt_tl'),
 (0.009166563280964006, 'num_il_tl'),
 (0.009139280338683036, 'mo_sin_rcnt_rev_tl_op'),
 (0.008985703137184642, 'inq_last_12m'),
 (0.008571143875018795, 'pct_tl_nvr_dlq'),
 (0.008381846634072418, 'acc_open_past_24mths'),
 (0.008367266779921955, 'open_acc'),
 (0.008087375509290336, 'num_sats'),
 (0.007959014814733507, 'num_bc_tl'),
 (0.007938460830499934, 'num_rev_tl_bal_gt_0'),
 (0.00787582927419742, 'num_op_rev_tl'),
 (0.007734476046391692, 'percent_bc_gt_75'),
 (0.007633332525171796, 'num_actv_rev_tl'),
 (0.007325623414390244, 'issue_d_Jan-2019'),
 (0.007183315570216045, 'num_tl_op_past_12m'),
 (0.007070322189142818, 'total_cu_tl'),
 (0.006892226262085272, 'open_il_24m'),
 (0.006816275103112239, 'open_rv_24m'),
 (0.006807607522154207, 'num_actv_bc_tl'),
 (0.006584381019004267, 'num_bc_sats'),
 (0.006405311217819653, 'open_act_il'),
 (0.006402509538537902, 'open_acc_6m'),
 (0.006128485622415899, 'mort_acc'),
 (0.006109914684559255, 'inq_fi'),
 (0.005659647162429604, 'issue_d_Feb-2019'),
 (0.0053952019866081585, 'open_rv_12m'),
 (0.005230590667907197, 'next_pymnt_d_Apr-2019'),
 (0.005078485538895371, 'tot_coll_amt'),
 (0.004992291124506376, 'inq_last_6mths'),
 (0.004944877877273311, 'next_pymnt_d_May-2019'),
 (0.004530601799472955, 'open_il_12m'),
 (0.003676330205409749, 'num_accts_ever_120_pd'),
 (0.003441737983469292, 'delinq_2yrs'),
 (0.002202255464648762, 'verification_status_Source Verified'),
 (0.0021700334108594893, 'verification_status_Verified'),
 (0.002101225332675528, 'verification_status_Not Verified'),
 (0.0020442322807367468, 'home_ownership_RENT'),
 (0.001988127672988634, 'home_ownership_OWN'),
 (0.0019298453730068384, 'application_type_Individual'),
 (0.001847785133201005, 'home_ownership_MORTGAGE'),
 (0.0017366759612909833, 'num_tl_90g_dpd_24m'),
 (0.0017206919697860725, 'pub_rec_bankruptcies'),
 (0.001678822925897434, 'pub_rec'),
 (0.0016305825312321162, 'application_type_Joint App'),
 (0.0014789906486948974, 'initial_list_status_f'),
 (0.0012532520732059336, 'initial_list_status_w'),
 (0.0010724327118413258, 'collections_12_mths_ex_med'),
 (0.0006390754097704172, 'home_ownership_ANY'),
 (7.728683378481631e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [17]:
# Train the Classifier
# YOUR CODE HERE
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(
    n_estimators=500,
    learning_rate=1,
    max_features=5,
    max_depth=3,
    random_state=0)
model.fit(X_train_scaled, y_train.ravel())
predictions2 = model.predict(X_test)

In [18]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
balanced_accuracy_score(y_test, predictions2)

0.5269141930521382

In [19]:
# Display the confusion matrix
# YOUR CODE HERE
cm2 = confusion_matrix(y_test, predictions2)
cm_df2 = pd.DataFrame(
    cm2, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)
cm_df2

          Predicted 0  Predicted 1
Actual 0           22           82
Actual 1         2697        14404

In [ ]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, predictions2))

### Final Questions

1. Which model had the best balanced accuracy score?

    YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.

4. What are the top three features?

    YOUR ANSWER HERE.